server.port: ${SERVER_PORT:8082}

spring:
  profiles.active: local-dev
  application:
    name: temporal-demo

logging.group:
  app:
    - org.febit.demo.temporal
  kafka:
    - org.apache.kafka

logging.level:
  app: info
  kafka: warn

spring.temporal:
  namespace:
  connection:
    target:
  workersAutoDiscovery:
    packages: org.febit.demo.temporal

spring.kafka:
  bootstrap-servers:
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # properties:
    # spring.json.add.type.headers: false
  consumer:
    max-poll-records: 1
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: org.febit.demo.temporal.workflow.model
      # spring.json.value.default.type: org.febit.demo.temporal.workflow.model.Message
    group-id:

management:
  endpoints.web.exposure.include: '*'
  server:
    port: 9999
  metrics:
    tags:
      application: ${spring.application.name}

app.temporal.producer:
  cron: '* * * * * *'
  batch-size: 200
  topic: temporal-demo

app.temporal.consumer:
  cron: '*/2 * * * * *'
  batch-size: 200
  topics:
    - ${app.temporal.producer.topic}
