global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'worker-actuator'
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 'worker:9999'
        labels:
          group: 'worker-metrics'
